# Required arguments don't have default values {#args-required}

## What's the problem

* In `sample()` neither `x` not `size` has a default value, suggesting that
  both are required, and the function would error if you didn't supply them.
  But `size` is in fact optional.

## Examples

* When subsetting a data frame `df[1]` returns a data frame, but `df[1, ]` 
  returns a vector.

## Exceptions to the rule

Sometimes, using a missing argument is the best you can do. 

*   Must supply one of a pair of arguments. `rvest::html_node(css, xpath)`
    `fct_other(keep, drop)`. `fct_lump(n, prop)`, `seq_range(n, by)`.
    
    Possibly too clever? Using `NULL` doesn't improve things because it would 
    imply that neither argument is needed. Maybe should be separate functions?
    That reduces typing `_prop` vs `, prop = `. Definitely true for `fct_lump()`
    which time has shown to need much greater extensibility.
    
    `rep()` as counter-counter example. It's really three functions.

*   `geom_abline()` - probably a sign that it should actually be two functions.

    ```{r, eval = FALSE}
    if (missing(mapping) && missing(slope) && missing(intercept)) {
      slope <- 1
      intercept <- 0
    }
    ```
    
    `geom_jitter()`, `geom_label()`. Use to add new interface on top of old.
    
*   `stringr::str_replace()`, `str_sub()`, `scale_*_manual()` - when one 
    argument can sometimes serve the role of two.

*   `readr::locale()`.

*   `purrr::reduce()` has an optional details argument called `init`. 
    When supplied, it serves as the initial value for the computation. But any 
    value (including `NULL`) can a valid value. Sometimes using a sentinel 
    value can be the right approach.
