# Magical default arguments {#args-magical-defaults}

```{r, include = FALSE}
source("common.R")
```

## What's the problem?

Some functions have default values that return different things when you run them interactively:

* In `hist()`, the default value of `xlim` is `range(breaks)`, and the default
  value for `breaks` is `"Sturges"`. `range("Sturges")` returns 
  `c("Sturges", "Sturges")` which clearly doesn't make sense.
  
* In `abind::abind()` the default value of `along` is `N`, which is computed
  inside the function.
  
* In previous versions of readr, `read_csv(progress = show_progress())`, 
  and `show_progress()` was an internal function.

If an argument depends on a value calculated inside the function, on an function that isn't available to the user, or has a default argument calculated in some non-standard way, we say it has a __magical default__.

## How do I fix it?

The typically fix for all these problems is simple: set the default value to `NULL` and conditionally perform the calculation inside the function. Using a default argument signals to the user that the argument is optional, and that the default value is not a constant, but requires some calculation.

If the calculation is complex, but the user might find it useful in other scenarios, compute it with an exported function. A good example is `readr::show_progress()`: it's used in every `read_` function and it's sufficiently complicated that you don't want to copy and paste it between functions. It's also nice to document it in its own file, rather than cluttering up file reading functions with incidental details.

This change does not alter the interface of the function so it can be made with changing the behaiour of any existing code.

## What if `NULL` is a valid value?

`ggplot2::waiver()`, `rlang::done()`.
