# Put the most important arguments first {#sec-args-data-details}

```{r}
#| include = FALSE
source("common.R")
```

## What's the pattern?

In a function call, the most important arguments should come first.
How can you tell what arguments are most important?
That's largely a judgement call that you'll need to make based on your beliefs about the function but there are some general principles that can help:

-   Arguments that determine the type of the output are typically the most important and should come first. This is particularly true for functions whose output is a transformation of one or more of the input arguments (e.g. `log()`, `stringr::str_replace()`, `dplyr::left_join()`).
-   Optional arguments (i.e. arguments with a default) are the least important, and should come last.
-   If the function uses `…`, the optional arguments should always come after `…`; see @sec-dots-position for more details.

Related patterns:

-   `...` can play the role of the data argument (e.g. when there are an arbitrary number of inputs), as in `paste()`.
    This pattern is best using sparingly, and is described in more detail in @sec-dots-data.

-   If the descriptor has a default value, I think you should inform the user about it, as in @sec-def-inform.

## What are some examples?

The vast majority of functions get this right, so we'll pick on a few examples which I think get it wrong:

-   I think the arguments to base R string functions (`grepl()`, `gsub()`, etc) are in the wrong order because they consistently make the regular expression (`pattern`) the first argument, rather than the character vector being manipulated.
    I think the character vector is more important because it's the argument the fundamentally determines the size of the output.

-   The first two arguments to `lm()` are `formula` and `data`.
    I'd argue that `data` should be the first argument; even though it doesn't affect the shape of the output (which is always an lm S3 object), it affects the shape of many important functions like `predict()`.
    However, the designers of `lm()` wanted `data` to be optional, so you could still fit models even if you hadn't collected the individual variables into a data frame.
    Because `formula` is required and `data` is not, `formula` must come first.

-   The first two arguments to `ggplot()` are `data` and `mapping`.
    Both data and mapping are required for every plot, so why make `data` first?
    I picked this ordering because in most plots there's one dataset shared across all layers and only the mapping changes.

    It's worth noting the layer functions, like `geom_point()`, flip the order of these arguments, because in an individual layer you're more likely to specify `mapping` than `data`, and in many cases if you do specify `data` you'll want `mapping` as well.
    This makes these the argument order inconsistent with `ggplot()`, but I think time has shown it to be a reasonable design decision.

## Why is it important?

This convention makes it easy to understand the structure of a function at a glance: the most important arguments are always on the left hand side, and it's obvious what arguments most affect the shape of the output.
Strongly connecting the shape of the first argument to the shape of output is what makes dplyr (data frames), stringr (character vectors), and purrr functions (vectors) easier to learn.
These families of functions represent transformations that preserve the shape while modifying the value.
When combined with the pipe, this leads to code that focuses on the transformations, not the objects being transformed.

These argument types as also affect how you *call* a function.
As discussed in @sec-call-data-details, you should never name data arguments, and always name details arguments.
This convention balances concision with readability.

## How do I remediate past mistakes?

Generally, it is not possible to remediate an existing exported function with this problem.
Typically, you will need to perform major surgery on the function arguments, and this will convey different conventions about which arguments should be named.
This implies that you should deprecate the entire existing function and replace it with a new alternative.
Because this is invasive to the user, it's best to do sparingly: if the mistake is minor, you're better off waiting until you've collected other problems before fixing it.

For example, take `tidyr::gather()` for example.
It has a number of problems with its design that made them hard to use.
Relevant to this chapter, is that the argument order is wrong, because you almost always want to specify which variables to gather, which is the fourth argument, not the second (after the `data`).
Because it wasn't possible to easily fix this mistake, we accumulated other `gather()` problems for several years before fixing them all at once in `pivot_longer()`.
