# User settable defaults {#def-user}

```{r, include = FALSE}
source("common.R")
```

## What's the pattern?

It's sometimes useful to give the user control over default values, so that they can set once per session or once for every session in their `.Rprofile`. To do so, use `getOption()` in the default value.

Note that this pattern should general only be used to control the side-effects of a function, not its compute value. The two primary uses are for controlling the apperance of output, particulary in `print()` methods, and for setting default values in generated templates.

If the computed values are different, you have an example of Chapter \@ref(args-hidden).

## What are some examples?

* `print()` + `options(digits, width)` 

* `install.packages()` + `options(repos)`

* `dplyr.show_progress`

* `scale_colour_continuous()`  - `type = getOption("ggplot2.continuous.colour", default = "gradient"))`

* `getOption("width")`, ` getOption("digits")`

* crayon/cli

* `usethis::use_description_defaults()`

## Why is it important?

## What are the exceptions?

`lubridate::wday()`: `week_start = getOption("lubridate.week.start", 7)`

## How do I use it?
