# (PART) Function interface {-}

# Introduction  {#function-interface}

The interface (aka API) of a function describes its external interface, independent of its internal implementation. The interface of a function has the following main components:

* Name
* Inputs
* Output value
* Errors
* Side effects

## Inputs

* Chapter \@ref(args-hidden): All inputs to a function should be explicit 
  arguments. Avoid functions that suprise the user by returning different 
  results when the inputs look the same.

### Default values

* Chapter \@ref(args-required): the absence of a default value should indicate
  that an argument is required; the presence of a default value should indicate
  that an argument is optional.

* Chapter \@ref(args-data-details): Required arguments should come before
  optional arguments.

* Chapter \@ref(args-independence): Make arguments as orthogonal as possible. 
  Avoid complex interdependencies.

* Chapter \@ref(args-enum): If a details argument can take one of a fixed set 
  of possible strings, record them in the default value and use `match.arg()`
  or `rlang::arg_match()` inside the function.
  
* Chapter \@ref(args-magical-defaults): Default values should return the same 
  answer when set directly.

* Chapter \@ref(args-defaults-short): Default values should be short. If
  you have a complex calculation, either use `NULL` or an exported function.

* Chapter \@ref(args-explain): If a default value is particularly important,
  as has non-trivial calculation, let the user know what it is.

* Chapter \@ref(args-user-defaults): Use `getOption()` to allow the user to 
  set default values.

### Dots

* Chapter \@ref(dots-position): `...` should be placed between the data and 
  details arguments.

* Chapter \@ref(dots-data): don't use `...` just to save the user from typing 
  `c()` (unless the function is purely for data structure creation).

* Chapter \@ref(dots-prefix): carefully consider if all other arguments need a 
  `.` prefix in order to reduce the chance of spurious matches.

* Chapter \@ref(dots-inspect): when using `...` with S3 methods, or passing on 
  to other functions that silently ignore mismatches, check that all inputs in 
  `...` are evaluated.

## Outputs

## Errors

* Chapter \@ref(err-constructor): if the same error is generated by multiple 
  functions, you should extract it out into its own function, an 
  __error constructor__.

## Other side-effects

