--- 
title: "Tidyverse design principles"
author: ["Tidyverse Team"]
site: bookdown::bookdown_site
output: bookdown::gitbook
github-repo: tidyverse/principles
documentclass: book
---

# Welcome {-}

This book has three aims:

* Identify function design __problems__ which lead to suboptimal outcomes.
* Describe useful __patterns__ that help solve common problems.
* Document key __principles__ that help you balance conflicting patterns.

It is used by the tidyverse team to promote consistency across packages in the core tidyverse. But you can also use it guide the design of your functions and packages in order to create APIs that feel "tidy", and fit in natural with tidyverse-centric workflows. It is a complement to <http://style.tidyverse.org>, which focusses on low-level code formatting.

This book will be under heavy development for quite some time; currently we are loosely aiming for completion in 2020. You'll find many chapters contain disjointed text that mostly serve as placeholders for the authors, and I do not recommend attempting to systematically read the book at this time.
