# Sneakily peeking

Functions are easier to understand if the return value only depends on the input arguments. If a function depends on a non-obvious input it's sneeky peeking. Peeking at global state is ok, but it should be obvious that it's happening.

* `data.frame()` sneakily peeks at a global option so that it's behaviour
  can differ in surprising ways.
  
* `sort()` sneakily peaks at `Sys.getlocale()`. `factor()` uses `order()`.

* `as.POSIXct()` depends on the the `TZ` env var.

* `Sys.time()` depends on the system time, but it's not a surprise.

* `read.csv(path)` depends not on the value of `path` but the contents of the 
  file at that location.

* Random number generates have to peak at the value of `.Random.seed` 
  and they also have to write to it. Otherwise every call to `runif()` would
  return the same values. But most of the time this abstraction is not 
  leaky; it just works and you don't have to worry about it.

## How to mitigate?

If you need to read from a setting external to the function or to R itself, it should be an argument to the function, where the default value makes it clear that the value is coming from somewhere else (i.e. not `NULL` or not using `missing()`ness). This will also make it easier to test your code.

## Related

* GITHUB_PAT
* auth and API keys
